In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [4]:
# instead of having to create a list and then creating the corresponding tensor, for certain
# tensors we can use shortcuts
zeros = torch.zeros((10, 10), dtype=torch.float32)
print(zeros)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [10]:
a = torch.arange(10, dtype=torch.float32)
b = torch.ones(10, dtype=torch.float32)

In [6]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# to calculate the sum of a vector's elements, we can matmul against
# a vector of ones
print(torch.matmul(a, b))

# we can also sum across a tensor
print(a.sum())

tensor(45.)
tensor(45.)


In [17]:
c = torch.arange(6)

# can reshape a tensor using view. View does NOT copy the underlying data.
d = c.view((2, 3))

# can also reshape using reshape. Reshape copies the underlying data.
e = c.reshape((2, 3))

In [18]:
print(d)
print(e)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [19]:
# can change a tensor along a dimension
f = torch.tensor([1, 2, 3])
g = f.unsqueeze(0)
h = f.unsqueeze(1)

In [20]:
print(f)
print(g)
print(h)

tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [23]:
g.squeeze(0)

tensor([1, 2, 3])

In [24]:
# we can look at matrices now
a = torch.rand((2, 3))
print(a)
print(a.mT) # correct way to do it now, a.t() is deprecated. mT = matrix transpose.
print(a.T)

tensor([[0.3222, 0.9663, 0.9107],
        [0.7941, 0.6435, 0.6292]])
tensor([[0.3222, 0.7941],
        [0.9663, 0.6435],
        [0.9107, 0.6292]])
tensor([[0.3222, 0.7941],
        [0.9663, 0.6435],
        [0.9107, 0.6292]])


In [25]:
b = torch.rand((2, 3, 4))

In [31]:
# (1,2,0) means that the first dimension (0) of the new tensor will be the second dimension (1) of the old tensor
# the second dimension (1) of the new tensor will be the third dimension (2) of the old tensor
# the third dimension (2) of the new tensor will be the first dimension (0) of the old tensor
c = b.permute(1, 2, 0)

In [29]:
print(f"b: {b}\tc: {c}")
print(f"b.shape: {b.shape}\tc.shape: {c.shape}")

b: tensor([[[0.8991, 0.4807, 0.0725, 0.8578],
         [0.2650, 0.3558, 0.7342, 0.0515],
         [0.8250, 0.5421, 0.0973, 0.6461]],

        [[0.3333, 0.3550, 0.9476, 0.0477],
         [0.5783, 0.6665, 0.5499, 0.6347],
         [0.1599, 0.0017, 0.6661, 0.1128]]])	c: tensor([[[0.8991, 0.3333],
         [0.4807, 0.3550],
         [0.0725, 0.9476],
         [0.8578, 0.0477]],

        [[0.2650, 0.5783],
         [0.3558, 0.6665],
         [0.7342, 0.5499],
         [0.0515, 0.6347]],

        [[0.8250, 0.1599],
         [0.5421, 0.0017],
         [0.0973, 0.6661],
         [0.6461, 0.1128]]])
b.shape: torch.Size([2, 3, 4])	c.shape: torch.Size([3, 4, 2])


In [36]:
# adding singleton dimensions. Can be done with None or unsqueeze
d = torch.arange(6)
print(f"Shape of d: {d.shape}")
print(f"Shape of d[None]: {d[None].shape}")
print(f"Shape of d.unsqueeze(0): {d.unsqueeze(0).shape}")
print(f"Shape of d[:, None]: {d[:, None].shape}")
print(f"Shape of d.unsqueeze(1): {d.unsqueeze(1).shape}")

Shape of d: torch.Size([6])
Shape of d[None]: torch.Size([1, 6])
Shape of d.unsqueeze(0): torch.Size([1, 6])
Shape of d[:, None]: torch.Size([6, 1])
Shape of d.unsqueeze(1): torch.Size([6, 1])


In [37]:
torch.arange(6)[::3]

tensor([0, 3])

In [42]:
torch.arange(6)[::10]

tensor([0])

In [78]:
test = torch.arange(12, dtype=torch.float32).reshape((1, 4, 3))

In [53]:
test

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])

In [52]:
test.max(dim=-1).values

tensor([[ 2,  5,  8, 11]])

In [57]:
test.max(dim=2).values

tensor([[ 2,  5,  8, 11]])

In [62]:
torch.unique(test.flatten()).sort().values

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
test2 = torch.arange(5, 15, dtype=torch.float32)

In [74]:
test2.greater(torch.mean(test.flatten(), dtype=torch.float32)).sum()

tensor(9)

In [81]:
(test2 > test.mean()).sum()

tensor(9)

In [89]:
test3 = torch.arange(9, dtype=torch.float32).reshape((3, 3))

In [91]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [90]:
torch.matmul(test3, torch.diag(torch.ones(3)))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [92]:
test3

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [93]:
test3 * torch.diag(torch.ones(3))

tensor([[0., 0., 0.],
        [0., 4., 0.],
        [0., 0., 8.]])

In [105]:
test.shape

torch.Size([1, 4, 3])

In [111]:
test.squeeze(0).shape

torch.Size([4, 3])

In [113]:
# get diagonal elements of test3
torch.diag(test)

RuntimeError: diag(): Supports 1D or 2D tensors. Got 3D

In [126]:
test_2d = torch.arange(12, dtype=torch.float32).reshape((3, 4))

In [120]:
test_2d

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [123]:
test_2d.flip(1).diagonal()

tensor([3., 6., 9.])

In [128]:
# turn into 1d tensor
test_2d.flatten().sum()

tensor(66.)

In [133]:
# change dtype to int
test_2d.int()

TypeError: cumsum() received an invalid combination of arguments - got (), but expected one of:
 * (int dim, *, torch.dtype dtype)
 * (name dim, *, torch.dtype dtype)


In [134]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4)).flatten()
# y = torch.where(x < torch.tensor([5]), torch.tensor([0]), x)
# the bottom is more efficient than the top since it doesn't require
# an implicit broadcasting step and extrapolates to multiple dimensions
# if needed.
y = torch.where(x < torch.tensor([5]), torch.zeros_like(x), x)

In [137]:
torch.zeros_like(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [140]:
torch.nonzero(x < torch.tensor([5]))

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [146]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = torch.tensor(5)

In [144]:
torch.nonzero(x < c)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0]])

In [150]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
def test_func(x, c):
    row, col = [], []
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i, j] < c:
                row.append(i)
                col.append(j)
    return torch.as_tensor([row, col])

In [148]:
test_func(x, c)

tensor([[0, 0, 0, 1],
        [0, 1, 2, 0]])

In [149]:
torch.nonzero(x < c).t()

tensor([[0, 0, 0, 1],
        [0, 1, 2, 0]])

In [154]:
(x < c).nonzero().t()

tensor([[0, 0, 0, 1],
        [0, 1, 2, 0]])

In [170]:
m = torch.BoolTensor(
    [
        [False, False, True, True, False],
        [False, True, True, True, False],
        [False, True, True, True, False],
        [False, True, True, True, False],
        [False, True, True, True, False]
    ]
)

In [171]:
m

tensor([[False, False,  True,  True, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False],
        [False,  True,  True,  True, False]])

In [172]:
x_5 = torch.arange(25).reshape((5, 5))

In [178]:
x_5*m

tensor([[ 0,  0,  2,  3,  0],
        [ 0,  6,  7,  8,  0],
        [ 0, 11, 12, 13,  0],
        [ 0, 16, 17, 18,  0],
        [ 0, 21, 22, 23,  0]])

In [174]:
def test_func(x, m):
    y = []
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if m[i, j]:
                y.append(x[i, j])
    return torch.as_tensor(y)

In [176]:
test_func(x_5,m)

tensor([ 2,  3,  6,  7,  8, 11, 12, 13, 16, 17, 18, 21, 22, 23])

In [180]:
# get elements of x_5*m that are nonzero
x_5[m]

tensor([ 2,  3,  6,  7,  8, 11, 12, 13, 16, 17, 18, 21, 22, 23])

In [181]:
x = torch.arange(6)
y = torch.arange(10, 16)

In [183]:
torch.diff(torch.cat((x, y)))

tensor([1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1])

In [189]:
x = torch.arange(6)
y = torch.arange(3, 9)

In [190]:
def test_func(x, y):
    count = 0
    for xi in x:
        for yi in y:
            if abs(xi - yi) < 1e-3:
                count += 1
                break
    return torch.as_tensor(count)

In [191]:
test_func(x, y)

tensor(3)

In [201]:
sum((x.unsqueeze(1) - y).abs().min(dim=1).values < 1e-3)

tensor(3)

In [202]:
test_input = torch.tensor([
    [74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000, 72.7000, 81.6000],
    [67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000, 58.0000, 64.1000]
])

In [215]:
test_input.shape

torch.Size([2, 10])

In [218]:
test_input.mean(dim=1)

tensor([74.4800, 68.4300])

In [222]:
test_input - test_input.mean(dim=1)[:, None]

tensor([[ 3.2001e-01,  1.3920e+01, -2.0080e+01, -1.7880e+01, -9.1800e+00,
          7.2200e+00,  2.0004e-02,  2.0320e+01, -1.7800e+00,  7.1200e+00],
        [-1.0300e+00,  1.5700e+00, -1.7330e+01, -1.0030e+01, -3.8300e+00,
          7.4700e+00,  1.6370e+01,  2.1570e+01, -1.0430e+01, -4.3300e+00]])

In [221]:
test_input.mean(dim=1)[:, None]

tensor([[74.4800],
        [68.4300]])

In [204]:
expected_output = torch.tensor([94.8000, 90.0000])

In [205]:
test_input[0].mean()

tensor(74.4800)

In [206]:
test_input[1].mean()

tensor(68.4300)